name: 'HugChat Issue Assistant'
description: 'Automatically respond to GitHub issues using HugChat AI'
author: 'Your Name'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  huggingface_email:
    description: 'HuggingFace account email'
    required: true
  huggingface_password:
    description: 'HuggingFace account password'
    required: true
  assistant_id:
    description: 'HugChat assistant ID'
    required: false
    default: '673e290837ec25016921608f'
  web_search:
    description: 'Enable web search for responses'
    required: false
    default: 'true'
  response_template:
    description: 'Custom template for the response. Use {response} as placeholder for the AI response'
    required: false
    default: |
      👋 Hello! Here's a response from HugChat:

      ---
      {response}
      ---

      *Note: I am a bot powered by HugChat. Please verify any information provided.*
  issue_filter:
    description: 'Labels to filter issues (comma-separated)'
    required: false
    default: ''
  add_labels:
    description: 'Labels to add to responded issues (comma-separated)'
    required: false
    default: 'hugchat-responded'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install hugchat
      shell: bash
    - run: ${{ github.action_path }}/hugchat_action.py
      shell: bash
      env:
        HUGCHAT_EMAIL: ${{ inputs.huggingface_email }}
        HUGCHAT_PASSWORD: ${{ inputs.huggingface_password }}
        ASSISTANT_ID: ${{ inputs.assistant_id }}
        WEB_SEARCH: ${{ inputs.web_search }}
        RESPONSE_TEMPLATE: ${{ inputs.response_template }}
        ISSUE_FILTER: ${{ inputs.issue_filter }}
        ADD_LABELS: ${{ inputs.add_labels }}
        GITHUB_TOKEN: ${{ github.token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_LABELS: ${{ toJSON(github.event.issue.labels) }}
